// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCxjgrvSL9q4b3GofhtvvA9ueduQafCNKk',
    appId: '1:421036401011:web:7a194d2b497b27f45d6506',
    messagingSenderId: '421036401011',
    projectId: 'rdp-todolist-910c5',
    authDomain: 'rdp-todolist-910c5.firebaseapp.com',
    storageBucket: 'rdp-todolist-910c5.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD3I3HzaEqoCLEY3bT7Per563BihcEGXb4',
    appId: '1:421036401011:android:35bdea30518d4d785d6506',
    messagingSenderId: '421036401011',
    projectId: 'rdp-todolist-910c5',
    storageBucket: 'rdp-todolist-910c5.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDQsH-fuRV610gPxpoXQHaGsJg4uLqEUHs',
    appId: '1:421036401011:ios:b8079a307d51049e5d6506',
    messagingSenderId: '421036401011',
    projectId: 'rdp-todolist-910c5',
    storageBucket: 'rdp-todolist-910c5.firebasestorage.app',
    iosBundleId: 'com.example.rdpTodolist',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDQsH-fuRV610gPxpoXQHaGsJg4uLqEUHs',
    appId: '1:421036401011:ios:b8079a307d51049e5d6506',
    messagingSenderId: '421036401011',
    projectId: 'rdp-todolist-910c5',
    storageBucket: 'rdp-todolist-910c5.firebasestorage.app',
    iosBundleId: 'com.example.rdpTodolist',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCxjgrvSL9q4b3GofhtvvA9ueduQafCNKk',
    appId: '1:421036401011:web:bad0a7d7d558b4475d6506',
    messagingSenderId: '421036401011',
    projectId: 'rdp-todolist-910c5',
    authDomain: 'rdp-todolist-910c5.firebaseapp.com',
    storageBucket: 'rdp-todolist-910c5.firebasestorage.app',
  );
}
